name: PlayerCounter
main: com.gmail.czeidlerwc.PlayerCounter.PlayerCounter
version: 1.5

commands:
  shutdownprep:
    description: Prepares the server to shut down and prevents players from loggin in.
    usage: /<command>
    permission: PlayerCounter.shutdownprep
    permission-message: You don't have <permission> permission
  cancelprep:
    description: Takes the server out of shut down prep mode
    usage: /<command>
    permission: PlayerCounter.cancelprep
    permission-message: You don't have <permission> permission